// The request body is provided in place
//? Sign up request
# @name login
POST {{base_url}}/auth/signup HTTP/1.1
Content-Type: application/json
Cookie: key=first-value

{
  "name": "Test username",
  "email": "jb@jb.jb",
  "password": "jb123"
}

###
@authToken = {{login.response.body.token}}

//? Sign in request
# @name register
POST {{base_url}}/auth/signin HTTP/1.1
Content-Type: application/json
Cookie: key=first-value

{
  "email": "jb@jb.jb",
  "password": "jb123"
}

###
@authToken = {{register.response.body.token}}


